# -*- coding: utf-8 -*-
"""AnaliseEscola.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KJW9XkGrphxxUgxy-DnHcx7XDQ16RqAg
"""

!pip install gspread oauth2client

"""Pega notas do google planilhas, lista das notas menores por aluno, bimestre, calculandoa média menor  que 6 e salva na planilha google."""

from google.colab import auth
auth.authenticate_user()

import gspread
from oauth2client.service_account import ServiceAccountCredentials
from collections import defaultdict

#Authenticate google sheet
from google.auth import default
creds, _ = default()


# Abrir a planilha
planilha = client.open("EE MSA Conselho de Classe 2024 Unificado")
aba = planilha.worksheet("Consolidado Notas")

# Obter os dados da planilha
dados = aba.get_all_records()

# Calcular médias por aluno
medias = defaultdict(lambda: {"NOTAS": [], "MEDIA": 0})
for aluno in dados:
    chave = (aluno["ANO"], aluno["TURMA"], aluno["BIMESTRE"], aluno["ALUNO"])
    nota = aluno["NOTA"]
    if nota != "" and nota is not None:
        if isinstance(nota, str):
            nota = float(nota.replace(",", "."))
        medias[chave]["NOTAS"].append(nota)

# Calcular médias e filtrar as baixas
medias_baixas = []
for chave, dados_aluno in medias.items():
    media = sum(dados_aluno["NOTAS"]) / len(dados_aluno["NOTAS"])
    if media < 6:
        medias_baixas.append({
            "ANO": chave[0],
            "TURMA": chave[1],
            "BIMESTRE": chave[2],
            "ALUNO": chave[3],
            "MEDIA": media,
        })

# Criar nova aba e inserir dados
try:
    planilha.add_worksheet("MEDIAS BAIXAS", len(medias_baixas) + 1, 5)
except gspread.exceptions.WorksheetAlreadyExists:
    planilha.del_worksheet(planilha.worksheet("MEDIAS BAIXAS"))
    planilha.add_worksheet("MEDIAS BAIXAS", len(medias_baixas) + 1, 5)

aba_medias_baixas = planilha.worksheet("MEDIAS BAIXAS")
aba_medias_baixas.append_row(["ANO", "TURMA", "BIMESTRE", "ALUNO", "MEDIA"])
for aluno in medias_baixas:
    aba_medias_baixas.append_row([aluno["ANO"], aluno["TURMA"], aluno["BIMESTRE"], aluno["ALUNO"], aluno["MEDIA"]])